### ISSUE TITLE
Alexa schema export

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#102]
<a href="https://github.com/JohnCalhoun"><img src="https://avatars1.githubusercontent.com/u/13800333?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JohnCalhoun](https://github.com/JohnCalhoun)**
_Thursday May 03, 2018 at 17:44 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/27_

----

needs to properly clean utterances

**Comment by JohnCalhoun** [comment]
could you example this more?

**Comment by servermachine** [comment]
With the direct cloudformation link, or building from master/develop, when updating Lex and then downloading the schema, the schema is still set to the default qnas. I can see the alexa and utterances files are also still the default. There's no errors on the web console.

**Comment by JohnCalhoun** [comment]
the alexa schema is built from the lex slot, which is only updated when you rebuild lex. 

we plan to fix this and have set up issue #79 to track
