### ISSUE TITLE
import export names of example/builtin functions

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#103]
<a href="https://github.com/JohnCalhoun"><img src="https://avatars1.githubusercontent.com/u/13800333?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JohnCalhoun](https://github.com/JohnCalhoun)**
_Thursday May 03, 2018 at 18:04 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/28_

----

**Comment by dontirun** [comment]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rstrahan](https://github.com/rstrahan)**
_Friday May 04, 2018 at 17:18 GMT_

----

The built-in lambda hook functions for Guided Tour (Next and Previous) and Quiz are assigned function names based on the CF stack name. When content is exported, these names are exported in the JSON, eg:

"l": "qna-QNA-dev-dev-master-3-Previous-PY",

When the JSON is then imported into a different stack, the build-in lambdas have different names, and so the imported lambda hooks fail to run. 

See user story: https://whhajira-a-relbapp-1mwzzjvyc03a5-881504368.us-east-1.elb.amazonaws.com/jira/browse/WHHA2017-122

**Comment by JohnCalhoun** [comment]
fixed in v2.1.0
