### ISSUE TITLE
SSML not working in web client voice

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#106]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Tuesday May 22, 2018 at 21:57 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/31_

----

Add SSML text to SSML Answer field of a question.. Expect that SSML to be used in lex web UI voice response , but there is no audio response.. only text.

Issue tracked down to newlines in the SSML..

This does NOT work:

<speak>
    Can you keep a secret? 
    <amazon:effect name="whispered">QnABot is not a real human.</amazon:effect>.
    Can you believe it?
</speak>

But this does work:

<speak>I want to tell you a secret. <amazon:effect name="whispered">I am not a real human.</amazon:effect>. Can you believe it?</speak>

We need to support formatted SSML (with newlines)

**Comment by JohnCalhoun** [comment]
fixed in 2.1.0
