### ISSUE TITLE
Stack update failed

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#107]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Wednesday May 23, 2018 at 21:19 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/32_

----

stack update on latest commits to develop branch rolls backs:
14:44:08 UTC-0400	UPDATE_FAILED	Custom::ESProxy	Index	Failed to update resource. "{\"type\":\"[InternalServiceError]\",\"status\":400,\"message\":\"Bad Request\",\"data\":{\"error\":{\"root_cause\":[{\"type\":\"index_already_exists_exception\",\"reason\":\"index [qna-dev-dev-master-4/MAflesazTKelzq6KzAVYMA] already exists\",\"index_uuid\":\"MAflesazTKelzq6KzAVYMA\",\"index\":\"qna-dev-dev-master-4\"}],\"type\":\"index_already_exists_exception\",\"reason\":\"index [qna-dev-dev-master-4/MAflesazTKelzq6KzAVYMA] already exists\",\"index_uuid\":\"MAflesazTKelzq6KzAVYMA\",\"index\":\"qna-dev-dev-master-4\"},\"status\":400}}"

**Comment by JohnCalhoun** [comment]
fixed in 2.1.0
