### ISSUE TITLE
stack create times out.. custom resource has uncaught error causing stack to time out

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#108]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Wednesday May 23, 2018 at 21:23 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/33_

----

Stack creation failed..

6:16:31 UTC-0400 | CREATE_FAILED | Custom::Kibana | Kibana | Custom Resource failed to stabilize in expected time

CFN Lambda logs: 
2018-05-23T19:16:36.033Z	cf952d78-5ebd-11e8-904b-b5fe92df865a	Error: Cannot find module './lib/con.js'
at Function.Module._resolveFilename (module.js:547:15)

Root cause is makefile dependency missing files in lambda/cfn/lib/kibana/lib - changes not picked up in build..

**Comment by JohnCalhoun** [comment]
fixed in 2.1.0
