### ISSUE TITLE
Feedback feature failing with 'Sorry, I was unable to process your message. Try again later.'

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#109]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Wednesday May 23, 2018 at 21:25 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/34_

----

Import feedback sample package
utterance - 'Feedback'
Error: Sorry, I was unable to process your message. Try again later.

**Comment by JohnCalhoun** [comment]
fixed in 2.1.0
