### ISSUE TITLE
Feedback feature fails in voice mode...

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#110]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Thursday May 24, 2018 at 20:04 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/35_

----

I can invoke the feedback feature in voice mode OK, but the spoken letter response isn't accepted - guessing because there is a period added.  I believe we previously observed and fixed this issue in the quiz handler, but maybe it was never fixed in the feedback handler?

See screenshot

![image](https://user-images.githubusercontent.com/10953374/40510912-194cae72-5f6c-11e8-8fb3-b92d4ada5cc0.png)

**Comment by JohnCalhoun** [comment]
this is fixedin 2.1.0
