### ISSUE TITLE
feedback doesn't work for questions that don't match any answers

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#111]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Friday May 25, 2018 at 20:33 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/36_

----

Tried typing 'help' which doesn't match any documents..
Bot returns 'You stumpted me!.."  but doesn't set 'previous' session attr..  So I can't leave feedback on this.. see screenshot:

![image](https://user-images.githubusercontent.com/10953374/40565105-3dc582f6-6039-11e8-8be6-5e0cb8e340f4.png)

**Comment by JohnCalhoun** [comment]
closing due to wontfix label
