### ISSUE TITLE
Usage logging should be insensitive to case and punctuation

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#115]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Tuesday May 29, 2018 at 16:07 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/40_

----

Usage logging should be insensitive to case and punctuation.. ie  i think these examples should be  visualized in Kibana as the same utterance:

Can I make a backup
can I make a backup
can I make a backup?
etc.

**Comment by JohnCalhoun** [comment]
so is the fix to strip punc, extra whitespace, and toLowerCase the utterances before logging to elasticsearch?
