### ISSUE TITLE
Fields in Document not appearing in the same order as Schema file

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#116]
For example in the qna.js schema file Lambda hook and Lambda hook arguments are next to each other.  They do not always appear next to each other in the designer UI

**Comment by JohnCalhoun** [comment]
why does this matter?

**Comment by dontirun** [comment]
Because users should get the same ordering each time. It's not a pleasant experience for eveything to be different. Plus it doesn't make sense when something like lambda hook arguments is the first thing in the list and then the lambda hook itself is the last thing.

**Comment by JohnCalhoun** [comment]
related to #99
