### ISSUE TITLE
Alexa Skill Instructions still mention echosim 

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#117]
Should be updated to use Alexa developer console

**Comment by rstrahan** [comment]
Changes text to:

Congratulations! Your QnABot skill is now ready to be used.

Enable testing (as shown below) and use the test page to try and test your new skill. 

### Alexa Device
To access your unpublished skill, register your Alexa device to the same account as your Amazon Developer account. If you have a device that is not registered to the right account, you can re-register it by following these directions: [Registering an Alexa-enabled Device for Testing](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/testing-an-alexa-skill#h2_register)

Ask questions in the form: *\"Alexa, ask Q and A, How do I use Q and A Bot?\"*  (Assuming your device wake word is 'Alexa')

Publish your skill if you want to make it available for others to use it from their own Amazon accounts.

**Comment by rstrahan** [comment]
Fixed in 2.1
