### ISSUE TITLE
Long questions (>140chars) break 'Rebuild Lex Bot' action

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#12]
Any question longer that 140 characters prevents "Rebuild Lex Bot" action from having any effect, though UI nevertheless reports 'Success".

Two aspects to this issue:  

 1. The Content Designer UI should detect and report bot rebuild failures.
 
2. QnABot should enforce the Lex slot type length limit by disallowing entry of questions longer than 140 characters.
  
Steps to reproduce
  
1. Add a long question to an item (> 140 characters), save item
2. Rebuild bot from ContentDesigner console
3. Observe Content designer reports 'Success'. Observe failures logged by Lambda 'Handler' function. Observe from Lex console that Lex bot is not actually rebuilt.

**Comment by JohnCalhoun** [comment]
Should questions be enforced to be shorter than 140 char or should the lambda function add a truncated version of the question to the SlotType?

**Comment by JohnCalhoun** [comment]
For now, lets fix this by enforcing questions to be less than 140 char in the Designer UI and also in the lambda handler.

**Comment by JohnCalhoun** [comment]
fixed in v2
