### ISSUE TITLE
File import Issue - Not working

### ISSUE THREAD

**Issue by rasuyom** [aws-samples/aws-ai-qna-bot#129]
When I manually add the questions and answer through the designer, I exported the json data then delete everything from the UI designer. But when I imported the exported json, nothing is happening. The data can't be uploaded back using the designer.

**Comment by ericchenmou** [comment]
As a workaround, you can host the file elsewhere and import by URL. I just did this with S3. Side note, I did have to modify my S3 bucket CORS policy to `<AllowedHeader>*</AllowedHeader>` instead of `<AllowedHeader>Authorization</AllowedHeader>`.

**Comment by papagala** [comment]
I initially tried to do that, but it still fails. Quick inspection by looking at developer tools and I see same error on both ways to upload json.

**Comment by papagala** [comment]
I was able to find a workaround. I opened developer tools in chrome and I hard coded the number of questions by opening the console and typing:

var i = {number of questions}

![image](https://user-images.githubusercontent.com/6526276/42068479-d9c820d0-7b11-11e8-8936-7c586d11db95.png)

And it works! I was able to migrate from version 2, to 2.1

**Comment by rstrahan** [comment]
Fix pushed to CfN S3 bucket: http://s3.amazonaws.com/aws-bigdata-blog/artifacts/aws-ai-qna-bot210/templates/public.json
Stack update will apply the fix.
