### ISSUE TITLE
Support SSML

### ISSUE THREAD

**Issue by tdoyle3** [aws-samples/aws-ai-qna-bot#15]
Please add the ability to support SSML in the responses.

**Comment by JohnCalhoun** [comment]
Should the Handler Lambda auto recognize the answer format or should the designer specify the format (adding that as an additional field to the QnADocument?)

**Comment by tdoyle3** [comment]
I would be happy with either solution. I've actually dug into the code yesterday, figured out that the change should be in handler, and now have it working for Alexa & am working on Lex. Be happy to share my code, but as I am new to this, you probably will come up with a more elegant solution!

**Comment by tdoyle3** [comment]
https://github.com/tdoyle3/aws-ai-qna-bot/commit/87354a844cf182e22c5cb62674072f87dba3edad

**Comment by JohnCalhoun** [comment]
I like what you have done! I wonder if there is a better way to convert the SSML to plain text? also your fixIntuitPhrases function is interesting, is there a reason you needed to do those modifications in the lambda and not before you upload the questions?

**Comment by tdoyle3** [comment]
Thank you! I'm sure there are better ways, but I didn't want to change something that wasn't SSML - so I limited it to just the appropriate tags. As far as fixIntuitPhrases, after I uploaded this, I thought that the function name should have been generic. The reason I want a function to do this is for simplicity and conformity. I plan to have multiple other teams creating, editing, and maintaining content that I will periodically import. If I asked them to add these SSML tags every time, there would be periodic misses and mistakes. This just simplifies it so they don't have to worry about it. I thought that these generic changes could be stored in a table somewhere instead of hardcoded, but that was more than I can take on at this point in my understanding of your code.

**Comment by tdoyle3** [comment]
Another issue to consider... With this implementation method, the SSML codes are included in the entry text, which I presume is what ElasticSearch is using to test against. Will this affect search results? For example, if a user searches on the term "alias", will articles which include the <sub alias=""> tag be incorrectly matched?

**Comment by JohnCalhoun** [comment]
I think #17 will provide a more flexible way to implement runtime manipulation of results.

yes, writing an answer as ssml will affect results. for example: a question with the word "speak" will be biased to answers written in ssml, since 
```
<speak>
```
 is common in ssml.  

hmm.... a few options
1) have two versions of an answer, plain text and optional ssml. if ssml is present then that is sent to polly/lex. essentially the designer would be responsible for maintaining both representations (UI would need to reflect this as well)

2) hack the ElasticSeach tokenizer/analyzer to do the ssml stripping, this would be easier on the designer but possibly harder to implement. may use something like [pattern tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenizers.html)

**Comment by tdoyle3** [comment]
Another option might be to do the ssml stripping when a record is saved, saving the plain version to another field in the record automatically, and pointing ElasticSearch to this field. This would simplify the ElasticSearch component, yet still allow for simplicity from the designer.

**Comment by tdoyle3** [comment]
Another option might be to do the ssml stripping when a record is saved, saving the plain version to another field in the record automatically, and pointing ElasticSearch to this field. This would simplify the ElasticSearch component, yet still allow for simplicity from the designer.

**Comment by tdoyle3** [comment]
Your formatting was a bit off, but I think I understand what you said, and I agree with the approach. Best of both worlds, and if in the future we want to give designers access to view/edit both fields, we can.

**Comment by JohnCalhoun** [comment]
I think this library will help implement this feature:
https://www.npmjs.com/package/pollymolly

**Comment by JohnCalhoun** [comment]
related to #38

**Comment by JohnCalhoun** [comment]
fixed in v2.0
