### ISSUE TITLE
How to update lambda functions only?

### ISSUE THREAD

**Issue by pdkn** [aws-samples/aws-ai-qna-bot#163]
Is it possible to 'update' lambda function only rather than the whole stack?

i.e `npm run stack dev/lambda update`

or better granularity

i.e `npm run stack dev/lambda update --group:fulfillment`

**Comment by bobpskier** [comment]
Only way at present that I'm sure will work is to update the entire stack. That said, if you only update a lambda function's source, the CF stack update should only apply updates to the lambda function being updated. Still takes a couple of minutes.

**Comment by pdkn** [comment]
Thanks bob, that’s correct. The main issue is speed of development as CF update is quite slow. My custom Lambdas are a different stack so quicker to update.
