### ISSUE TITLE
Kendra and Comprehend allways in null ("sentimentResponse": null)

### ISSUE THREAD

**Issue by portacha** [aws-samples/aws-ai-qna-bot#193]
Where can i see the comprehend data in this new version?
i Read that this version can extract sentiment but cant find where are this data..
I try using QNAFreeText but in kendra i see this always. 

`        "recentIntentSummaryView": [
          {
            "intentName": "fulfilment_I*****",
            "checkpointLabel": null,
            "slots": {
              "slot": "hi can i told you a secret"
            },
            "confirmationStatus": "None",
            "dialogActionType": "Close",
            "fulfillmentState": "Fulfilled",
            "slotToElicit": null
          }
        ],
        "sentimentResponse": null,
        "kendraResponse": null,
        "origQuestion": "i have a low positive mind so i need kill people and kill myself",
        "errorFound": false
      },`

**Comment by rstrahan** [comment]
Hi @portacha  

If you use the sample package "ConditionalChainingDemo" you can try it out.. the sample let's you enter free text comment at the end, and will display the sentiment.  The sentiment is also returned to the client in the Sentiment field of the demo.comment Session attribute.
 
![image](https://user-images.githubusercontent.com/10953374/88218695-61d2fa80-cc2e-11ea-82cc-b90d64d6f7d5.png)

**Comment by portacha** [comment]
I use that but the response is null. Do I need to do any additional configuration to activate this function?

`{
  "_index": "***-metrics_20200715_160729",
  "_type": "_doc",
  "_id": "49608922123521413653787558777455468104875316732386869250.0",
  "_version": 1,
  "_score": null,
  "_source": {
    "entireRequest": {
      "_event": {
        "messageVersion": "1.0",
        "invocationSource": "FulfillmentCodeHook",
        "userId": "******",
        "sessionAttributes": {
          "navigation": "{\"next\":\"\",\"previous\":[],\"hasParent\":true}",
          "userLocale": "en",
          "elicitResponseNamespace": "demo.comment",
          "previous": "{\"qid\":\"40.leave.feedback\",\"a\":\"Please give us some feedback about this selection.\",\"alt\":{\"markdown\":\"***Please give us some feedback about this selection?***\"},\"q\":\"Leave Us Some Feedback\"}",
          "elicitResponse": "QNAFreeText",
          "userDetectedLocaleConfidence": "0.9968931674957275",
          "userDetectedLocale": "en",
          "demo": "{\"comment\":{\"FreeText\":\"I liked this review very much.\"}}"
        },
        "requestAttributes": null,
        "bot": {
          "name": "****",
          "alias": "live",
          "version": "3"
        },
        "outputDialogMode": "Text",
        "currentIntent": {
          "name": "fulfilment_Intentt****",
          "slots": {
            "slot": "The observers providing you with feedback will need positive reinforcement, too! Saying “That's great advice, I hadn't thought of it"
          },
          "slotDetails": {
            "slot": {
              "resolutions": [],
              "originalValue": "The observers providing you with feedback will need positive reinforcement, too! Saying “That's great advice, I hadn't thought of it"
            }
          },
          "confirmationStatus": "None"
        },
        "inputTranscript": "The observers providing you with feedback will need positive reinforcement, too! Saying “That's great advice, I hadn't thought of it",
        "recentIntentSummaryView": [
          {
            "intentName": "fulfilment_I****",
            "checkpointLabel": null,
            "slots": {
              "slot": "Leave Us Some Feedback"
            },
            "confirmationStatus": "None",
            "dialogActionType": "Close",
            "fulfillmentState": "Fulfilled",
            "slotToElicit": null
          }
        ],
        "sentimentResponse": null,
        "kendraResponse": null,
        "origQuestion": "The observers providing you with feedback will need positive reinforcement, too! Saying “That's great advice, I hadn't thought of it"
      },
      "_settings": {
        "ENABLE_DEBUG_RESPONSES": "false",
        "ES_USE_KEYWORD_FILTERS": "true",
        "ES_NO_HITS_QUESTION": "no_hits",
        "ES_USE_FUZZY_MATCH": "true",
        "ES_KEYWORD_SYNTAX_TYPES": "NOUN,PROPN,VERB,INTJ",
        "ES_SYNTAX_CONFIDENCE_LIMIT": ".20",
        "ES_MINIMUM_SHOULD_MATCH": "2<65%",
        "ES_PHRASE_BOOST": "4",
        "ES_SCORE_ANSWER_FIELD": "false",
        "ERRORMESSAGE": "Unfortunately I encountered an error when searching for your answer. Please ask me again later.",
        "EMPTYMESSAGE": "You stumped me! Sadly I don't know how to answer your question.",
        "DEFAULT_ALEXA_LAUNCH_MESSAGE": "Hello, Please ask a question",
        "DEFAULT_ALEXA_STOP_MESSAGE": "Goodbye",
        "SMS_HINT_REMINDER_ENABLE": "true",
        "SMS_HINT_REMINDER": " (Feedback? Reply THUMBS UP or THUMBS DOWN. Ask HELP ME at any time)",
        "SMS_HINT_REMINDER_INTERVAL_HRS": "24",
        "IDENTITY_PROVIDER_JWKS_URLS": [],
        "ENABLE_MULTI_LANGUAGE_SUPPORT": "true",
        "MINIMUM_CONFIDENCE_SCORE": 0.6,
        "ALT_SEARCH_KENDRA_INDEXES": [],
        "ELICIT_RESPONSE_MAX_RETRIES": 3,
        "ELICIT_RESPONSE_RETRY_MESSAGE": "Please try again?",
        "ELICIT_RESPONSE_BOT_FAILURE_MESSAGE": "Your response was not understood. Please start again.",
        "ELICIT_RESPONSE_DEFAULT_MSG": "Ok. ",
        "ENABLE_REDACTING": "false",
        "REDACTING_REGEX": "\\b\\d{4}\\b(?![-])|\\b\\d{9}\\b|\\b\\d{3}-\\d{2}-\\d{4}\\b",
        "DEFAULT_USER_POOL_JWKS_URL": "*********"
      },
      "_type": "LEX",
      "_userId": "*******",
      "question": "The observers providing you with feedback will need positive reinforcement, too! Saying “That's great advice, I hadn't thought of it",
      "session": {
        "navigation": {
          "next": "",
          "previous": [],
          "hasParent": true
        },
        "userLocale": "en",
        "elicitResponseNamespace": "demo.comment",
        "previous": {
          "qid": "40.leave.feedback",
          "a": "Please give us some feedback about this selection.",
          "alt": {
            "markdown": "***Please give us some feedback about this selection?***"
          },
          "q": "Leave Us Some Feedback"
        },
        "elicitResponse": "QNAFreeText",
        "userDetectedLocaleConfidence": 0.9955196380615234,
        "userDetectedLocale": "en",
        "demo": {
          "comment": {
            "FreeText": "I liked this review very much."
          }
        }
      },
      "_preferredResponseType": "PlainText",
      "_userInfo": {
        "InteractionCount": 3,
        "UserId": "******",
        "FirstSeen": "Thu Jul 23 2020 18:46:04 GMT+0000 (Coordinated Universal Time)",
        "LastSeen": "Thu Jul 23 2020 18:48:51 GMT+0000 (Coordinated Universal Time)",
        "TimeSinceLastInteraction": 22.214
      },
      "_info": {
        "es": {
          "address": "*****",
          "index": "*****",
          "type": "qna",
          "service": {
            "qid": "*****I-ESQidLambda-1*****",
            "proxy": "****-ESProxyLambda-******"
          }
        }
      }
    },
    "entireResponse": {
      "type": "PlainText",
      "message": "Ok. ",
      "session": {
        "navigation": "{\"next\":\"\",\"previous\":[],\"hasParent\":true}",
        "userLocale": "en",
        "previous": "{\"qid\":\"40.leave.feedback\",\"a\":\"Please give us some feedback about this selection.\",\"alt\":{\"markdown\":\"***Please give us some feedback about this selection?***\"},\"q\":\"Leave Us Some Feedback\"}",
        "userDetectedLocaleConfidence": "0.9955196380615234",
        "userDetectedLocale": "en",
        "demo": "{\"comment\":{\"FreeText\":\"The observers providing you with feedback will need positive reinforcement, too! Saying “That's great advice, I hadn't thought of it\"}}"
      },
      "card": {
        "send": false,
        "title": "",
        "text": "",
        "url": ""
      },
      "_userInfo": {
        "InteractionCount": 4,
        "UserId": "*******",
        "FirstSeen": "Thu Jul 23 2020 18:46:04 GMT+0000 (Coordinated Universal Time)",
        "LastSeen": "Thu Jul 23 2020 18:49:13 GMT+0000 (Coordinated Universal Time)",
        "TimeSinceLastInteraction": 22.214
      },
      "plainMessage": "Ok. "
    },
    "utterance": "the observers providing you with feedback will need positive reinforcement too saying thats great advice i hadnt thought of it",
    "answer": "Ok. ",
    "topic": "",
    "clientType": "LEX",
    "datetime": "2020-07-23T18:49:13.441Z"
  },
  "fields": {
    "datetime": [
      "2020-07-23T18:49:13.441Z"
    ]
  },
  "sort": [
    1595530153441
  ]
}`

**Comment by bobpskier** [comment]
QnABot's use of Kendra and the configuration of questions using the QNAFreeText ElicitResponseBot are separate concepts. If QnABot can't find an answer in its own ElasticSearch database and it is configured with a Kendra index id, it will search Kendra for an answer as well, and present results that are found. This is a fallback mechanism. 

When QNAFreeText is configured as an ElicitResponseBot for a qid, it allows the user to respond with any text. For example a user may ask a question that is answered by QnABot in its normal fashion. As part of the response, the question may chain to a feedback question. A chaining rule might be to chain to the question 'Did this help' which tells QnABot to lookup the question 'Did this help'. The configuration for 'Did this help' would include the use of QNAFreeText as an ElicitResponseBot. This configuration also specifies the namespace to store the result of the user's answer. As an example lets assume the namespace is 'feedback'. After the user enters feedback, the Lex session attributes will contain a property named "feedback". It will include both the FreeText value and the identified sentiment. In my example as part of the Lex session attributes this might be:

"feedback": "{\"FreeText\":\"thanks for the information\",\"Sentiment\":\"POSITIVE\"}",

With version 4.1.0 of QnABot, each use of QnAFreeText, once complete, should provide a Lex session property that matches the configured namespace. Within this property, FreeText should contain the value uttered or typed by the user and Sentiment should contain one of the standard values from Comprehend sentiment analysis.
