### ISSUE TITLE
Precise branching logic in Amazon Lex Content Designer based on qid matching instead of question matching

### ISSUE THREAD

**Issue by plkmo** [aws-samples/aws-ai-qna-bot#195]
Hi,
I have been trying to implement branching tree in my chatbot following this blog link https://aws.amazon.com/blogs/machine-learning/creating-a-question-and-answer-bot-with-amazon-lex-and-amazon-alexa/#chaining.

According to the above, conditional chaining rule specifies the logic for the next question that the current query should be directed to. However, this re-directing in conditional chaining rule is based on the question field, not qid field. I noticed that it may not give the correct matching question each time due to question matching errors in elastic search, and this is especially so when the size of QnA data pairs gets huge.

Eg. For instance for conditional chaining rule (SessionAttributes.dia2.Yes_No=="Yes")?"dia2#yes":"dia2#no", it does not correctly redirect to the qid in which the question "dia2#yes" falls under even though the session attribute returns "Yes", due to matching confusion with other question-answer pairs.

Is it possible for **conditional chaining to redirect to the exact qid instead of to the question field?** This to me makes much more sense in a precise branching logic tree as it eliminates the uncertainty brought about by question-to-question matching by elastic search.

Thanks.

**Comment by rstrahan** [comment]
Hi @plkmo - Thanks for this. Yes, I think we can implement a qid variant of conditional chaining targets. To maintain backward compatibility, maybe we can use target string like "QID::<qid_value>" to identify qid targets. I'll add to our backlog. Thanks for the request.

**Comment by plkmo** [comment]
Hi @rstrahan, thanks for your support. Thats great, I look forward to the update. 
Meanwhile, I am trying to see if I can use lambdas/changing matching settings to circumvent this issue, but its not an ideal solution.

**Comment by mykiwibuddy** [comment]
Just a newbie myself at this but I had same desire to jump to a specific question. Quick fix. Use underscores in questions -- prevents words being broken up.  I'd use something like this:
 'dia2_' + SessionAttributes.dia2.Yes_No
this results in dia2_yes and dia2_no
Downside is that it requires ES to then match the question, whereas QID jump would not.

**Comment by rstrahan** [comment]
Change is queued for next release.  Specify QID in chaining rule by using string like `QID::<qid>`  e.g. `QID::Admin.001`. 
Note, the new `QID::<qid>` syntax can also be used from the webUI, say as button values if/when you prefer to target a specific QID (exact query) rather than rely on question matching.

**Comment by plkmo** [comment]
@rstrahan ok great thanks!
@mykiwibuddy Thanks, I have tried underscores and some other delimiters but there are still quite some QnA matches that leaked through them.
