### ISSUE TITLE
Chaining based on Lambda result - while updating session variables

### ISSUE THREAD

**Issue by mykiwibuddy** [aws-samples/aws-ai-qna-bot#196]
Scenario is that I gather info using Elicit Response then make an API call. Based on API result - which I store in session, I'd like to jump to a specific follow-up path.  
Issues: chaining returns a string (for chaining) so does not allow session update. Hook can update session - but how can I then jump to one of multiple follow-up questions? 
Additionally, I could use a hook and then chaining (based on session attributes), but chaining only fires when Elicit response is configured.
So, what's the recommended method to branch following an API call (using a Lambda)? Or, perhaps chaining can be available without Elicit Response. Or is API call and branch not recommended?

**Comment by rstrahan** [comment]
Hi @mykiwibuddy - I see the issue. You want to make a chaining decision based on an API call AND you want to store the results of that API call in a session attribute. Our chaining lambda support does not allow for session updates. 

Adding support for the Lambda chaining function to optionally return a modified session object in addition to the string for chaining, I think this would address the issue.  Will investigate.

**Comment by rstrahan** [comment]
pushed fix to branch queued for next release. 
Chaining Rule Lambda can now optionally return an 'event' object in the payload (just like Lambda hooks) in place of a simple string (also supported for backward compatibility). 
Chaining is controlled by the value set by the lambda in the event.req.question field.
The chaining lambda can change other aspects of the session, for example, set session attributes in event.res.session, similarly to a lambda hook function.
This hopefully addresses the use scenario noted - the chaining lambda can now call the API, set the req.question field to determine the next document in the chain, and also set session attributes to be used downstream.
(Also note #195  - specify exact QID to query as an alternative to question matching query, using question string of the form "QID::<qid>")
