### ISSUE TITLE
Redirect to different QnA instance in lambda hooks

### ISSUE THREAD

**Issue by plkmo** [aws-samples/aws-ai-qna-bot#224]
Hi,

I can't seem to find the syntax that the lambda function hook should modify in event['res'] object, in order to redirect the user to a specific QID. Can someone point it out please? Thanks.

**Comment by rstrahan** [comment]
Hi @plkmo  -  Lambda hooks are intended to be used to modify or replace the matched QID answer programatically.. They don't have a built in mechanism for redirecting to a different QID.  However, you can use Document Chaining to match a new QID.
A document chaining rules can be implemented as a Lambda function which can modify the event is all the same ways as a Lambda Hook, but which can also redirect to a new QID by modifying event.req.question.  See https://aws.amazon.com/blogs/machine-learning/creating-a-question-and-answer-bot-with-amazon-lex-and-amazon-alexa/#chaining

**Comment by plkmo** [comment]
Hi @rstrahan, thanks for your reply, I will try document chaining lambdas then.
