### ISSUE TITLE
SSML tags seem to not work in Alexa skills

### ISSUE THREAD

**Issue by Dudemanguy** [aws-samples/aws-ai-qna-bot#225]
Hi, I'm having trouble getting SSML tags to work when using the Alexa skill. From the log output, it seems like it always receives a PlainText message instead of an SSML one. The question JSON I'm using is just this.

```
{
  "qna": [
    {
      "args": [
        ""
      ],
      "next": "",
      "a": "Reading this number: 578.",
      "r": {
        "buttons": [
          {
            "text": "",
            "value": ""
          }
        ],
        "subTitle": "",
        "imageUrl": "",
        "title": ""
      },
      "t": "",
      "elicitResponse": {
        "response_sessionattr_namespace": "",
        "responsebot_hook": ""
      },
      "alt": {
        "markdown": "",
        "ssml": "<speak>Reading this number: <say-as interpret-as=\"digits\">578</say-as>.<speak>"
      },
      "conditionalChaining": "",
      "l": "",
      "qid": "Testing",
      "type": "qna",
      "selected": false,
      "q": [
        "Can you read a number?"
      ]
    }
  ]
}
```

If I run this in the client url website, it works as expected (the number is read back as digits). If I run this in the Alexa Skill I have hooked up to the bot, it reads back the number as the actual number. This is using 4.2.0.

**Comment by rstrahan** [comment]
Hi @Dudemanguy  - you are right.. we recently introduced a bug - in a recent commit to fix SSML for Amazon Connect, we broke it for Alexa! So sorry about that.  Testing a fix now, and will be in our next release soon. Thanks so much for reporting it.

**Comment by Dudemanguy** [comment]
Thanks for the quick response and fix!
