### ISSUE TITLE
QNADateBot Behavior

### ISSUE THREAD

**Issue by Dudemanguy** [aws-samples/aws-ai-qna-bot#228]
Hi, I just had a question about how the QNADateBot behaves. I suspect it might just be because of how the `AMAZON.DATE` slot works but maybe someone can point me in the right direction here.

Basically, if a user types in an ambiguous date like "October 20th", the bot will assume the user wants 2021 and prompts with October 20th, 2021 since that date has already passed. On the other hand, if a user types a date in the near future like "December 1st", then it assumes it's this year. Is there anyway to get the bot to always handle those types of queries as the current year the user is asking them in? In our usage, we are referring to events that happened in the past for these dates and not the future. I understand the current behavior is more intuitive for reserving a date for example.

**Comment by rstrahan** [comment]
Hi @Dudemanguy  - the QNADateBot uses the AMAZON.DATE slot type provided by Amazon Lex - see https://docs.aws.amazon.com/lex/latest/dg/built-in-slot-date.html
Unfortunately the behavior is not customizable - if you want to refer to a date that has passed I think you need to make the year explicit.

**Comment by Dudemanguy** [comment]
Ah, I was afraid of that. Thanks for the info.
