### ISSUE TITLE
add contributing 

### ISSUE THREAD

**Issue by JohnCalhoun** [aws-samples/aws-ai-qna-bot#23]
I would like to formalize and communicate that we are following the git branching method described here: http://nvie.com/posts/a-successful-git-branching-model/

as well as the AWS requirements for community contributions

**Comment by PabTorre** [comment]
do you have a link to theAWS requirements for community contributions?

**Comment by matthewberryman** [comment]
I tend to use github keywords myself in commit messages, e.g. "fixes #issue_number description_of_fix" or otherwise reference the #issue_number and provide a short but clear description.
