### ISSUE TITLE
QNAFreeText Response Bot not created with CF stack

### ISSUE THREAD

**Issue by dfetterman** [aws-samples/aws-ai-qna-bot#231]
The documentation mentions that QNAFreeText was added in version 4.1.0. Launching a stack using the link in the README (https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=QnABot&templateURL=http://aws-bigdata-blog.s3.amazonaws.com/artifacts/aws-ai-qna-bot/templates/public.json) creates a stack and a number of Lex bots such as QNAEmailAddressBot, QNADayOfWeekBot, QNADateBot, etc. It does not create a QNAFreeText bot or a QNAFreeText custom slot type. 

Am I missing something?

**Comment by rstrahan** [comment]
Hi @dfetterman - QNAFreeText capability was added in 4.1.0. While, for a QnABot user perspective, it behaves like other response bots, it is not actually implemented as a nested Lex bot. It captures the full text of the user's utterance, and we already have that available in the incoming request, so we don't need to call a nested Lex bot to fill the slot. The logic for QnAFreeText is implemented in [lexRouter.js](https://github.com/aws-samples/aws-ai-qna-bot/blob/master/lambda/fulfillment/lib/middleware/lexRouter.js) 
Cheers
Bob

**Comment by dfetterman** [comment]
@rstrahan, thanks for the reply. It helped me get a better grip on how this is supposed to work. I'm posting the following to hopefully help anyone else who gets hung up on this in the future.

To actually use the QNAFreeText capability, I created a new card and within the card I set the following parameters... 

```
Elicit Response: ResponseBot Hook
QNAFreeText 
Elicit Response: Response Session Attribute Namespace
my.response 
Document Chaining: Chaining Rule
'finish feedback' 
```

I created another new card called "finish feedback". In the markdown answer section, to see the actual sentiment I added `{{SessionAttributes.my.response.Sentiment}}` and to see the actual content of the user free text input `{{SessionAttributes.my.response.FreeText}}`

I imagine if I had the second card hit a lambda function instead of replying with an answer it would have posted this information to the lambda function event which will be useful. 

Maybe I missed it but I didn't see the slot name for that QNAFreeText uses documented anywhere. I was able to find that it on line 96 of [lexRouter.js](https://github.com/aws-samples/aws-ai-qna-bot/blob/master/lambda/fulfillment/lib/middleware/lexRouter.js). **The slot name is FreeText.**

**Comment by rstrahan** [comment]
Thanks @dfetterman  - I think you got it!
FYI - the QnABot blog post (www.amazon.com/qnabot) has a section titles "Response Bots" which notes the slot names for  QNAFreeText. 

![image](https://user-images.githubusercontent.com/10953374/100656879-69f92000-331b-11eb-8594-06b992c5b3f2.png)

Also, there's  demo package that does pretty much the same thaing that you explained above, using QNAFreeText to ask for feedback and then finally showing the sentiment for the feedback.

*...use Content Designer to import the new sample package, ConditionalChainingDemo. Use the Web UI, entering Start to see the first question.*

> I imagine if I had the second card hit a lambda function instead of replying with an answer it would have posted this information to the lambda function event which will be useful.

yes, absolutely. The world is your oyster with Lambda Hooks :)

Thanks for posting, and good luck!
