### ISSUE TITLE
Interaction count starts at zero instead of one

### ISSUE THREAD

**Issue by tommcgee57** [aws-samples/aws-ai-qna-bot#235]
It's a problem that {{UserInfo.InteractionCount}} starts at zero only after your first question. So if I have:

So far, you have interacted with me {{UserInfo.InteractionCount}} times.

in my answer block, after my first question "what color is the sky" it will give the answer, "blue," and repeat:

So far, you have interacted with me 0 times.
Which is obviously not correct. What can I do for this? I want to give users a running total of how many questions they have asked because I want them to limit themselves to 10.

**Comment by rstrahan** [comment]
Hi @tommcgee57  - thanks for logging the issue. I staged a fix - if you are building from source you can try it now from the fix branch, otherwise it will be in our next release.

**Comment by tommcgee57** [comment]
Thanks, Robert.

Unfortunately, I’m trying to implement this through the AWS dashboard and I have absolutely no idea where these files are stored or how to get at them to make the fix. I’ll watch for the next version to come out.

Best,

Tom
