### ISSUE TITLE
Responding with multiple lines from Lambda

### ISSUE THREAD

**Issue by Jgeissler14** [aws-samples/aws-ai-qna-bot#237]
I am looking for a solution to allow lambda to respond with line breaks in the text. I am using python in a lambda function to call job openings from a dynamoDB table and would like each job to be on a seperate line in one response to the user. Here is what it currently looks like 
![image](https://user-images.githubusercontent.com/66270580/102808338-30518d00-438e-11eb-885e-a6714453e409.png)
I have attempted to use /n, <br> and other similar combinations but have had no luck. The line breaks are read and not shown in the plain text, but the line break itself doesn't appear.

**Comment by rstrahan** [comment]
You can use [markdown ](https://www.markdownguide.org/basic-syntax/) to insert line breaks (as \</br\> or as two spaces at end of line followed by new line), numbered lists, etc. using the Lex Web UI client.   Markdown alternate messages are sent to the Lex Web UI using the session attribute: `res.session.appContext.altMessages.markdown`
