### ISSUE TITLE
Issue when importing the Connect Flow in non-US-East locations

### ISSUE THREAD

**Issue by notesgnome** [aws-samples/aws-ai-qna-bot#247]
I created the QnA bot from the Launch Stack (sydney), and all went well. I then followed the steps to create a default connect flow. That all went well as well (no errors, etc.)

However, it wouldn't work, and fell through to errors all the time. I couldn't work out why (although it was late at the time). I even uninstalled QnA, and resinstalled it with the same error.

I then discovered that the JSON file that designer cleverly creates has a small flaw. It gets the correct name of the Lex, however it says it is US-East; hence, calling it fails.

Here is the section of JSON for a Sydney installation ("name":"BotRegion","value":"**us-east-1**")
longer version:
`"parameters":[{"name":"Text","value":"prompt","namespace":"User Defined"},{"name":"TextToSpeechType","value":"text"},{"name":"BotName","value":"QnABot_name"},{"name":"BotAlias","value":"live"},{"name":"BotRegion","value":"us-east-1"}`

**Comment by rstrahan** [comment]
Ah!  Thanks for reporting this!  That we need to fix!

**Comment by kthomas-amzn** [comment]
Fixed in 4.7.2
