### ISSUE TITLE
QNAFreeText max characters

### ISSUE THREAD

**Issue by dfetterman** [aws-samples/aws-ai-qna-bot#266]
Does the built-in response bot QNAFreeText have a max character limit and is it sanitizing the input in any way?

**Comment by rstrahan** [comment]
Hi @dfetterman 

1. QnABot doesn't impose a limit but Lex default limits apply.. 15secs of speech, or 1024 unicode characters.. see https://docs.aws.amazon.com/lex/latest/dg/gl-limits.html

2. What user enters is what you get, along with sentiment detected. You could further process the free text using a lambda hook to 'sanitize' it as needed.
