### ISSUE TITLE
Build Failure: Mac 11.4 (20F71)

### ISSUE THREAD

**Issue by jfischburg-lifemesh** [aws-samples/aws-ai-qna-bot#278]
I've been unable to build this project on Mac 11.4 (20F71). Has anyone successfully built this recently? Any suggestions? I've attached the log.
[2021-07-04T13_57_56_973Z-debug.log](https://github.com/aws-samples/aws-ai-qna-bot/files/6759997/2021-07-04T13_57_56_973Z-debug.log)

**Comment by bobpskier** [comment]
The log indicates you are building with nodejs 16.4.0. At present time builds will succeed with nodejs version 12.16.1. Can you use nvm and set the current nodejs version to 12.16.1? Nodejs runtime 12 is the version qnabot deploys for its Lambda functions. Next up is to target nodejs 14 which is the next supported lambda runtime.

**Comment by jfischburg-lifemesh** [comment]
Brilliant! Thank you @bobpskier.
