### ISSUE TITLE
Markdown Messages through Lambda

### ISSUE THREAD

**Issue by ojo-john** [aws-samples/aws-ai-qna-bot#284]
Does QnABot support markdown messages through lambda? Im trying to pass this "The Q and A Bot uses [Amazon Lex](https://aws.amazon.com/lex) and [Alexa]" as a string to event.res.message but it only shows "Amazon Lex" without having the link.

**Comment by bobpskier** [comment]
QnABot supports a markdown response field. You'll see this in the Advanced section in the Designer UI when editing a question. Valid markdown can be specified. QnABot returns this value in the appContext.altMessages session variable. The companion LexWebUi (which is also the sample web client in QnABot) will use this value and render markdown in the UI. See https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#markdown-and-html-support. 

`{
    "appContext":{
        "altMessages":{
            "markdown":"# hello!"
        }
    }
}`

If you are using a Lambda hook in QnABot for a question, the same session attribute can also be set by the lambda function in the result object.

**Comment by ojo-john** [comment]
Thank you!
