### ISSUE TITLE
CloudFormation issue during install:  `TooManyBuckets`

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-ai-qna-bot#285]
Seeing this issue across multiple attempts to install:

```
You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets;
```

Any thoughts on how to get passed this?

**Comment by bobpskier** [comment]
AWS accounts by default are limited to 100 S3 buckets. You'll need to use an account that has room for the 7 buckets created by the stack. Either a limit increase in the AWS account is needed or a different AWS account needs to be used for deployment.
