### ISSUE TITLE
mailto URIs not supported

### ISSUE THREAD

**Issue by matthewberryman** [aws-samples/aws-ai-qna-bot#32]
## Expected Behavior
```
[email link](mailto:example@example.net)
```
should result in a mailto link

## Actual Behavior
No link. Maybe #29 will help address this?

## Steps to Reproduce the Problem

  1. Create a mailto link in markdown for a response
  2. Send a query that triggers that response

**Comment by JohnCalhoun** [comment]
yes, this is related to #29, the current regex that looks for links is too restrictive on the form of the url between the parentheses. The fix will just assume whatever is between he parenthesis in a markdown link is a link.

**Comment by JohnCalhoun** [comment]
will be fixed when markdown support comes

**Comment by JohnCalhoun** [comment]
this is fixed with new markdown support
