### ISSUE TITLE
Develop Branch: Admin user email is hardcoded in build/templates/test/master.json

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#35]
## Expected Behavior

Admin email address should not be hardcoded in build/templates/test/master.json
Suggest prompt for email address, and/or require email address as environment var or parameter.

## Actual Behavior

Admin email address is hardcoded to:
"Email": "jcalho@amazon.com",
When stack is created non interactively by a different user (using "npm run stack test/master up"), the Cognito QnABot signup email is not received. 

## Steps to Reproduce the Problem

  1. As a user that is not jcalho, create stack from cloned repo (develop branch) using 'npm run stack test/master up'
  2. try to log in to Content Designer UI

## Specifications

  - Version:
  - Platform:

**Comment by JohnCalhoun** [comment]
maybe add the script in npm install that clears that field, or have it tied to /config.json

**Comment by JohnCalhoun** [comment]
fixed in v2
