### ISSUE TITLE
Support Alternate Voice and Text Responses, with option for markdown (text) and SSML (voice)

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#38]
Purpose : support different answers for each mode, e.g. more concise answers for voice, more elaborate answers for text.
Lex Web UI should render markdown text response as rich text in messaging interface.. other clients will simply render the markdown text.
Optional SSML used for voice responses for both Lex and Alexa

**Comment by JohnCalhoun** [comment]
maybe, since lex should be aware of the client (facebook, alexa, web-ui, twit etc..) we have answers for specific clients (this answers would not be used for search in elasticsearch)

**Comment by JohnCalhoun** [comment]
A thought)
as we have seen before, field names other than q,a,l have no need to be hardcoded anywhere in the back end. meaning, users can index questions with arbitrary fields and w/ lambda hooks #39  they could use those fields for what ever processing they wanted to do. no need to limit those extra fields.
 UI would need to be adjusted to support reading/writinig arbitary fields.
