### ISSUE TITLE
QnABot Lambda Extension Hooks

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#39]
Purpose: Support (a) item navigation and (b) dynamic content in responses through QnABot extension hooks implemented as AWS lambda functions.
Implementation: 
1.	Content Designer UI supports (optional) selection and assignment of existing Lambda function to any item. Function selection pick list filterable by function name substring or tag.
2.	When extension hook function is specified, QnABot handler will call the referenced function, passing as input:
a.	full session/intent context (utterance, session attributes, etc.)
b.	elasticsearch response containing all fields of all matched items
3.	The function will return a response object containing one of the following response types:
a.	reply: { <Lex/Alexa response object>}
This gives complete control of bot response to the extension hook function, including voice, text, attachments, and session attributes. 
Use cases are many: 
- Dynamic responses of all sorts, for example: “When is the next race?”, “Will there be an event tomorrow?”, etc.
- Navigate through ordered items, for example: “Where can I go now?”, “What’s the next topic?”, etc. 
- Dynamically look up answers from external sources
- Log and respond to user feedback, eg: “That answer was no good”
- Perform actions, eg: “Email me me a copy of that answer”
- and much more – the possibilities are endless.
b.	redirect: { <New question> }
This allows the extension hook function to redirect the QnABot handler to a different item, rather than providing a direct response to the current item.
Use cases: 
- Auto navigation through guided content, for example: “Next item please” could redirect QnAbot to automatically query the next question in an ordered list of questions corresponding to a guided curriculum or tour.
4.	QnABot handler will 
a.	passback a ‘reply’ response object from an extension hook to Lex/Alexa
b.	reenter handler with a new question contained in a ‘redirect’ response object
5.	QnABot handler should also preserve most recent previously asked question + matched item response in a session attribute, so that extension hook functions can access previous Q&A details for feedback logging and navigation purposes.
6.	Provide QnABot Lambda Extension hook ‘function blueprints’ to simplify and standardize:
a.	Logging of inputs and outputs
b.	Normalizing Lex and Alexa request objects
c.	Creating Lex and Alexa response objects

**Comment by JohnCalhoun** [comment]
If we think of the Lambda hooks as middleware then there are three possible places to register the lambdas
1. to individual questions
2. to topics 
3. globaly (great for analytics)

**Comment by JohnCalhoun** [comment]
User will need to supply two things 
* lambda Arn to be called
* IAM role that can be assumed so the fulfillment lambda can invoke the custom lambda

**Comment by JohnCalhoun** [comment]
I think there are two lambda hooks
1) preproccess-lambd(sync call)
called before ES query, called for all requests. this would allow designers to make changes to the ES request and possibly redirect behavior. 

2) postprocess-lambda(sync call)
called after ES query. lambda name comes from lambda field in response. this would allow dynamic responses

3) finish lambda (async call)
called before sending response. this is where you could put analytics

**Comment by JohnCalhoun** [comment]
problem) 
if a lex request has to call 4 lambdas (pre/post-process, response, and itself) and all have to cold start then a lex request could take a longtime to finish.

**Comment by rstrahan** [comment]
Yeah, I think 4 lambdas is overkill, and I share your latency concern. For now, I believe most/all known extension use cases can be met with support for a single optional Lambda registered at the item level.

**Comment by JohnCalhoun** [comment]
fixed in v2
