### ISSUE TITLE
Guided Navigation 

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#40]
Purpose: Use extension hook mechanism to support guided navigation, forward and backward, through an ordered list of items. Example use cases:
-	Using QnABot for a guided virtual tour or facilities or artifacts, user can say “next room please”, or “next item please”, and the extension function will redirect QnABot to answer the next question in the ordered list. Or “go back”, “Previous item” item to navigate backward in the list.
-	Using QnABot for training curricula, user can say “next topic please”, and the extension function will redirect QnABot to answer the next question in the ordered list of topic questions.  

Implementation:
1.	Automatically derive default question order from list of items sorted by ID.
2.	Provide easy mechanism for user to supply custom ordered list of questions
a.	One way this could be done it to leverage the existing content designer to specifiy the ordered list of questions in a well-known QnA item ID, eg: ‘RESERVED.QnA.Question.Order” that can be queried by the navigation function to retrieve the ordered list of questions..  Other methods are also possible, but may require extra implementation effort.

**Comment by JohnCalhoun** [comment]
If we allowed multiple topics per question you could implement this using overlapping topics

| qid |topic_1 | topic_2 |     
|----|--------|--------|
| 1 | A | - | 
| 2 | B | A |
| 3 | C | B | 

and so on

**Comment by JohnCalhoun** [comment]
fixed in 2.1
