### ISSUE TITLE
Log User Feedback

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#41]
Purpose: Use extension hook mechanism to support ability for users to provide and log feedback on the quality of the answer received from previous question. Example use cases:
-	User can say “That did not answer my question”, or “That answer is wrong”, etc. (Utterances supported to be determined by content designer). Utterance matched to item created in content designer, which calls this Lambda extension function, which in turn logs the feedback in CloudWatch metrics and CloudWatch logs, making it easy for Content Administrator to assess user satisfaction with the answers, and therefore make informed adjustments to the content as needed.

**Comment by JohnCalhoun** [comment]
Maybe AWS comprehend's sentiment analysis has a role to play here?

**Comment by JohnCalhoun** [comment]
fix in 2.1
