### ISSUE TITLE
ElasticSearch 6.0

### ISSUE THREAD

**Issue by JohnCalhoun** [aws-samples/aws-ai-qna-bot#43]
Upgrade ElasticSearch from 5.1 => 6.0 

why?
best practice to use newest version if possible

**Comment by pdkn** [comment]
Upgrade ElasticSearch from 5.1 => 7.0 ?

**Comment by bobpskier** [comment]
It is on our wishlist. Fairly significant changes plus upgrade methodology to get there.

**Comment by dtt101** [comment]
Version 4.0.0 ships with 7.4 - ref: https://github.com/aws-samples/aws-ai-qna-bot#version-400

**Comment by rstrahan** [comment]
Yup - I guess we can close this issue now at last :)
