### ISSUE TITLE
Development branch: Answer field should not be limited to 140 chars 

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#48]
## Expected Behavior

Don't restrict length of answer field

## Actual Behavior

![image](https://user-images.githubusercontent.com/10953374/34080375-9910fbec-e30a-11e7-823c-d50761a364a1.png)

## Steps to Reproduce the Problem

Enter string > 140 chars into answer field

**Comment by JohnCalhoun** [comment]
increased limit to 8000 char (lex and alexa limit)

**Comment by JohnCalhoun** [comment]
fixed in v2
