### ISSUE TITLE
Development branch: refreshing page should not cause log out

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#49]
## Expected Behavior

browser refresh should simply refresh, while keeping login context

## Actual Behavior

browser refresh is logging out the session
 
![image](https://user-images.githubusercontent.com/10953374/34080615-43fcf82c-e30f-11e7-857e-d204279fd0bd.png)

## Steps to Reproduce the Problem

  1.  Login
  2.  Hit browser refresh
  3.  Observe how it makes you log in again

**Comment by JohnCalhoun** [comment]
fixed in v2
