### ISSUE TITLE
Development branch: Alexa instructions - Skill information page errors

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#50]
1. Typo - should be 'Custom Interaction Model'
2. Don't invert font colors for skill and invokation names (makes it look like these are buttons to be clicked (per usage of this style on previous page). Suggest using monospaced (courier) font for text to be entered.
3. This page in the developer console has a 'Save' button, not a 'next' button

![image](https://user-images.githubusercontent.com/10953374/34080822-0b1b3c0a-e312-11e7-8648-ad4a94650b61.png)

**Comment by JohnCalhoun** [comment]
fixed in v2
