### ISSUE TITLE
Development branch - Alexa instructions - Interaction model

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#51]
Refers to button below, but there is no button on this page. (Buttons seem to appear on next page)
Also, maybe use 'courier' / monospaced font instead on inverted color for text to be entered.

Suggest revisit of Alexa instructions to ensure instructions match developer console steps, page by page.

![image](https://user-images.githubusercontent.com/10953374/34080851-63de41ca-e312-11e7-98b9-a91be78662f8.png)

**Comment by JohnCalhoun** [comment]
fixed in v2
