### ISSUE TITLE
Update CF template to support Fault Tolerant Elastic Search domain (2xinstances)

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#53]
## Expected Behavior

Customer lost QnA Content after node failure on default single instance ES domain. 

While the blog does state that the dafault ES domain should be increased to 2 instances for production deployments, we could increase awareness if QnABot CF template supported provisioning fault tolerant elastic search domain (2 x Instances) by default. User should still be allowed to provision single node non-fault-tolerant domain for non-production / non-critical deployments.

**Comment by JohnCalhoun** [comment]
fixed in v2
