### ISSUE TITLE
con filename reserved in windows

### ISSUE THREAD

**Issue by Mike-Last** [aws-samples/aws-ai-qna-bot#57]
## Expected Behavior
git clone git@github.com:awslabs/aws-ai-qna-bot.git works on windows

## Actual Behavior
error: unable to stat just-written file lambda/handler/lib/con.js: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

## Steps to Reproduce the Problem

  1. On a windows machine with git configured
  2. git clone git@github.com:awslabs/aws-ai-qna-bot.git

It seems files named con are reserved and this code base contains 2 entries.

Thanks for the excelent QnA bot though!

**Comment by JohnCalhoun** [comment]
those files have been removed in the develop branch during refactoring of the lambda code.
once we merge develop into master this should no longer be an issue

**Comment by JohnCalhoun** [comment]
fixed in v2

**Comment by mayfield2333** [comment]
FY: I have this same problem with a file named aux.sh in a personal repo, unrelated to this project:

> error: unable to stat just-written file hints/aux.sh: No such file or directory
