### ISSUE TITLE
Document Item IDs that begin with a number are not findable in QnABot Client

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#65]
## Expected Behavior
Asking a question will return the corresponding best match document

## Actual Behavior
Document will not return in Client if Document Item ID begins with a number.
Document is will show up and is still ranked in the Designer

## Steps to Reproduce the Problem

  1. Create a Document with an Item ID that begins with a number ex. "1.Start" and fill in a question
  2.Attempt to get a response in the Client
 
@JohnCalhoun

**Comment by JohnCalhoun** [comment]
two options
- enforce that ids cannot start with number
- fix whatever is causing the problem

i think first option is fine, most programing languages don't allow variable names to start with a number. Is there a compelling reason to start an id with a number?

**Comment by dontirun** [comment]
It makes it easier to go between rooms. For example if people are asking questions in 1.ARoom then it is easier to change to 2.BRoom when trying to figure out what room we need to navigate to next

**Comment by JohnCalhoun** [comment]
ok, i see

**Comment by JohnCalhoun** [comment]
i was not able to reproduce this in develop branch.
i made the following document 

id) 1.a
q) who am i
a) me

client response back correctly. did you try rebuilding lex bot?
