### ISSUE TITLE
Answers containing '&' characters cause bot to fail in voice mode

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#68]
## Expected Behavior

Ampersands should either be supported, or converted to the word 'and' for voice responses.

## Actual Behavior

Chat bot responds "Sorry, I had an error handling this conversation."

![image](https://user-images.githubusercontent.com/10953374/36432135-697c7d16-1627-11e8-9fc1-b818f80a2abd.png)

Browser console displays error:

client.js:7144 converser error: Error: Invalid Bot Configuration: Invalid SSML request (Service: AmazonParrot; Status Code: 400; Error Code: InvalidSsmlException; Request ID: f8fc9e25-1650-11e8-a371-958f7fe4f76a)

## Steps to Reproduce the Problem

  1. Create a document in Content Designer, with an '&' in the answer field

![image](https://user-images.githubusercontent.com/10953374/36432223-b0267488-1627-11e8-96dc-5399b8e2cc43.png)

  2. Use lex Web UI to query that document using voice, eg "do ampersands work?"

  3. Observe error (Note is works OK in text mode)

**Comment by JohnCalhoun** [comment]
Makes sense, lex/polly dont support a number of special characters. Any suggestions on solution
1) enforce alpha-numeric characters in anwsers
2) strip out characters in fulfillment

**Comment by JohnCalhoun** [comment]
i tested this out and did not get the error
