### ISSUE TITLE
Creating a document from the designer with a + character in the "Item Id" field causes cognito errors

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#73]
## Expected Behavior
You can add a document with a + sign in the the Item Id without issues

## Actual Behavior
"the plus sign is messing up the url that is used to create a document, which is make the designer think the credentials are expired or dont work, loggin you out." Document does not get added

## Steps to Reproduce the Problem

  1. Create a Document with an Item Id that contains a +
 

## Specifications

  - Version:
  - Platform: 
@JohnCalhoun

**Comment by JohnCalhoun** [comment]
fixed in v2.0.0
