### ISSUE TITLE
Stack can fail and roll back when launched in multiple regions (eg us-east-1 and eu-west-1) because of CloudWatch Dashboard name conflict

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#81]
## Expected Behavior

Stacks in different regions should be isolated, independed.. Existance of stack in one region should not affect success of launching a stack in another region.

## Actual Behavior

Stack can fail and roll back when launched in multiple regions (eg us-east-1 and eu-west-1) because of CloudWatch Dashboard name conflict..  CW Dashboards are global resources, so when a second stack in a different region tries to create a new Dashboard with the same name as stack in first region, it fails. 

## Steps to Reproduce the Problem

  1. Launch QnABot in us-east-1  (npm run up)
  2. Launch QnABot in eu-west-1  (change config.json region.. then npm run up)... Fails.

## Specifications

  - Version:
  - Platform:

**Comment by JohnCalhoun** [comment]
fix in 2.1
