### ISSUE TITLE
QnABot web client errors in voice mode - Sorry, I had an error handling this conversation.

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#83]
## Expected Behavior

No errors!

## Actual Behavior

As reported by blog reader "Owen": 

> Successfully ran cloud formation template and the client works as expected when typing a question.
> 
> Using the microphone elicits:
> "Sorry, I had an error handling this conversation"
> 
> But in the log from the Lambda Fulfilled cloudwatch widget I can see that it received and translated my voice and submitted the correct response as fulfilled. Just doesn't show in the client.
> 

Problem was also seen ans reported by another internal user installing QnABot for the first time.

## Steps to Reproduce the Problem

  1.  Install QnABot in an account that have not previously had a Lex bot installed.
  2. Use voice in the web UI to interact with the bot. Observe error:

![image](https://user-images.githubusercontent.com/10953374/40720082-9295e69c-63e3-11e8-879e-bd4dc4b5bea6.png)

Browser console shows:

converser error: Error: Invalid Bot Configuration: Lex is unable to assume the Service-Linked Role AWSServiceRoleForLexBots necessary to synthesize a speech response for this request.  Please confirm that this role exists within your account, or create it with the IAM Console or by using the CreateServiceLinkedRole operation in the IAM SDK.

Deeper investigation shows permissions error reported by CFN Lambda function when attemptiing to create the Lex ServiceLinked Role:

> 2018-05-30T11:51:26.892Z	c83a1564-63ff-11e8-8506-052c80a4cc0d	{ AccessDenied: User: arn:aws:sts::895572318605:assumed-role/QnABotTestNewAccount-CFNLambdaRole-1PM1JIKEXHL3R/QnABotTestNewAccount-CFNLambda-13C7ZQOSG5RA4 is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::895572318605:role/aws-service-role/lex.amazonaws.com/AWSServiceRoleForLexBots
> at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:47:29)

**Comment by JohnCalhoun** [comment]
this is fixed in 2.0.1
