### ISSUE TITLE
Questionnaire Bot provides wrong custom responses

### ISSUE THREAD

**Issue by adam-imeson** [aws-samples/aws-ai-qna-bot#84]
## Expected Behavior

Questionnaire Bot custom responses will trigger one response for a correct answer and the other response for an incorrect answer.

## Actual Behavior

If there are two custom-response questions in a row and the user gets the first wrong and the second right, the bot will respond to the second, correct response with the custom response intended for an incorrect answer.

## Steps to Reproduce the Problem

  1.  Import https://s3.amazonaws.com/public-blog-image-hosting/example-questionnaire-bot-quiz.json
  2. Change the ExampleQuiz.3 "Incorrect Answer Response" field such that it isn't the same as the "Correct Answer Response" field.  
  3. Go to the client and type "Take the example quiz."
  4. Get the second question wrong and the third question right.
  5. Note that the bot responds with the contents of ExampleQuiz.3's "Incorrect Answer Response" field.

## Specifications

  - Version: Stack that spins up when you use this CF link.  https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=QnABot&templateURL=http://s3.amazonaws.com/qnabot-guided-navigation-blogpost-template/artifacts/aws-ai-qna-bot/templates/public.json

**Comment by JohnCalhoun** [comment]
this is fixed in 2.1.0
