### ISSUE TITLE
Questionnaire Bot Lambda function needs updated IAM permissions

### ISSUE THREAD

**Issue by adam-imeson** [aws-samples/aws-ai-qna-bot#85]
## Expected Behavior

questionnaire bot works when i ask to take a quiz

## Actual Behavior

the *-Quiz-JS lambda function breaks with the message 

Failed { AccessDeniedException: User: arn:aws:sts::682179654853:assumed-role/QnABot-STAAAACK-ExampleLambdaRole-GV8GIPVWBVRZ/qna-QnABot-STAAAACK-Quiz-JS is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:682179654853:function:QnABot-STAAAACK-ESQidLambda-FZE0PN913M73

## Steps to Reproduce the Problem

  1.  Build the stack with the below CloudFormation link.
  2.  Import https://s3.amazonaws.com/public-blog-image-hosting/example-questionnaire-bot-quiz.json
  3.  Go to the client and type "take the example quiz."
  4.  Check CloudWatch logs for the Questionnaire Bot Lambda function's log streams.

## Specifications

  - Version: version that spins up when you use this CF link https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=QnABot&templateURL=http://s3.amazonaws.com/qnabot-guided-navigation-blogpost-template/artifacts/aws-ai-qna-bot/templates/public.json

**Comment by JohnCalhoun** [comment]
what branch is this on?

**Comment by adam-imeson** [comment]
I don’t know. I didn’t put together that CF setup. I would assume the develop branch because it was internal.

**Comment by JohnCalhoun** [comment]
this is fixed in 2.1.0
