### ISSUE TITLE
Multiple stacks cause errors in permissions and example lambda hooks

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#87]
Because of how example lambda functions and other functions are now aliased creating errors pointing to the correct example function in the account when having multiple stacks.
 
Steps to Reproduce. 

1. Create a QnABot stack
2. Create a second QnABot stack
3. Attempt to use example lambda hooks like Next and Previous in second stack

**Comment by JohnCalhoun** [comment]
fixed in v2.1
