### ISSUE TITLE
Lex Bot rebuild throws error on first launch: Request Failed: error response from endpoint

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#91]
## Expected Behavior

Lex bot should build with no errors

## Actual Behavior

Error reported - see screenshot or error and console

Object
response
:
{type: "[InternalServiceError]", message: "", data: "{message=Missing required key 'versionOrAlias' in …RequiredParameter, time=2018-06-01T01:23:29.784Z}"}

![image](https://user-images.githubusercontent.com/10953374/40816132-219d4142-6519-11e8-8f07-3f5eb891386d.png)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:

**Comment by rstrahan** [comment]
This happens a *lot* - didn't used to happen.. We need to fix it..

**Comment by JohnCalhoun** [comment]
agreed, i am looking into this but i do not see a clear explanation yet

**Comment by JohnCalhoun** [comment]
Found problem, logic error in the LexStatusLambda that got introduced when we started using a lex alias for the bot. i have a fix and am testing it now.

**Comment by tchnlgst** [comment]
Having same issue now, and using the latest release. Any thoughts as to where to look for the root cause?

**Comment by rstrahan** [comment]
Hi @tchnlgst - Can you please clarify exactly the issue you are now experiencing with the latest build, include error messages that you see and/or screenshots. Can you reproduce the problem on a fresh installation? Please provide detailed steps to reproduce, and we'll look into it, or give you better troubleshooting pointers. Thanks!

**Comment by tchnlgst** [comment]
I had opened another issue in the Open issues, so I'm unsure if you want me to respond here.

Essentially, i've installed the stack twice. It begins working fine for a few days. Then anytime you access the designer, you get the error "Request Failed: error response from endpoint". This happens even if you haven't added any questions or made configuration changes; the error appears all of a sudden after a few days after installation. Like I said, I've deployed the cloudformation stack twice. I opened the case after it started throwing the same error a few days after the second fresh installation.

My endpoint is at:
https://72fufvhn86.execute-api.us-west-2.amazonaws.com/prod/pages/designer

<img width="617" alt="Screen Shot 2021-03-08 at 1 50 28 PM" src="https://user-images.githubusercontent.com/6992173/110386990-df107b80-8015-11eb-8284-53e26b8054ef.png">
<img width="1439" alt="Screen Shot 2021-03-08 at 1 51 51 PM" src="https://user-images.githubusercontent.com/6992173/110387003-e2a40280-8015-11eb-8f1d-819ac3d60840.png">
<img width="925" alt="Screen Shot 2021-03-08 at 1 35 35 PM" src="https://user-images.githubusercontent.com/6992173/110387011-e5065c80-8015-11eb-924f-a611f1712718.png">
<img width="931" alt="Screen Shot 2021-03-08 at 1 36 00 PM" src="https://user-images.githubusercontent.com/6992173/110387027-ea63a700-8015-11eb-8d1d-2a7b67b5760a.png">
<img width="930" alt="Screen Shot 2021-03-08 at 1 34 55 PM" src="https://user-images.githubusercontent.com/6992173/110387036-ecc60100-8015-11eb-9a5c-c4bd5a7c5c80.png">

**Comment by rstrahan** [comment]
I want to say the most likely explanation is expired credentials, which would be resolved by logging out / logging in again to Designer.. OR hitting refresh should also take you back to login if credentials have expired. Does that explanation plausibly fit what you are seeing?
Can you also try a different browser, or logging in from a different machine?  (I want to see if the problem is related to time since install, or time since login)
If not, then can you open your browser Developer Tools to see if there are clues reported in either the Console or Network views?

**Comment by tchnlgst** [comment]
It's not really expired credentials. I've already tried that, as well as other browsers. Same issue. 

I also created new cognito users with Admin privileges to the solution, and the get the same message now. What I don't understand is why this starts working fine for a few days, and then after a few days after deployment, the errors start appearing. It happened twice in the last 30 days, during two separate deployments.

I've provided screenshots of the console views in the last message, which referenced 404 errors. The Network view also has a few errors as seen below:

<img width="1254" alt="Screen Shot 2021-03-08 at 2 37 38 PM" src="https://user-images.githubusercontent.com/6992173/110391233-0f5b1880-801c-11eb-89db-bd8b5ce2cec4.png">

**Comment by tchnlgst** [comment]
I believe the issue might be with Elasticsearch. When I preview those errors, I get a "cluster_block_exception". See screenshot below. 

So perhaps a few days after deployment Elasticsearch encounters an issue and I get the errors I'm getting.

<img width="1304" alt="Screen Shot 2021-03-08 at 2 57 18 PM" src="https://user-images.githubusercontent.com/6992173/110392953-9c9f6c80-801e-11eb-8523-d99bf0fcf79d.png">

I see that same error under the elasticsearch service indices tab.

<img width="1165" alt="Screen Shot 2021-03-08 at 2 59 37 PM" src="https://user-images.githubusercontent.com/6992173/110393192-fa33b900-801e-11eb-98fa-a04954e3ccbf.png">

**Comment by rstrahan** [comment]
Oh, that's interesting.. Can you check the status of the Amazon Elasticsearch domain in the console?  Maybe it's gone unhealthy?

**Comment by tchnlgst** [comment]
Yes, it does appear to have gone unhealthy, and I assume this is what happened the first time I deployed the cloudformation stack and the error appeared. I thought redeploying would solve it, but for some reason the elasticsearch cluster goes into an unhealthy state. Any pointers or reasons you can think of why this happens?

<img width="1179" alt="Screen Shot 2021-03-08 at 3 23 43 PM" src="https://user-images.githubusercontent.com/6992173/110395058-54824900-8022-11eb-9cfc-f2e94c256779.png">

**Comment by rstrahan** [comment]
We just released QnABot 4.5.0 yesterday (the blog just got updated today).. this release will upgrade existing t2.small.elasticsearch instances to the newer t3.small.elasticsearch instances.  Since you mentioned it's been running for more than two days, then I know you can't be already on 4.5.0 :)  Can you upgrade (or re-install and restore your content) to get the latest instance types.  We also recommend going with 4 nodes for production workloads now - better fault tolerance.  Let me know if that helps.

**Comment by tchnlgst** [comment]
Good to know. I will redeploy the entire solution. We didn't have any content so we don't need to restore anything. I'll let you know if the issue appears again. Fingers crossed that the new release fixes it.

**Comment by PawanLRN** [comment]
I'm facing exactly same error "Request Failed : error response from endpoint "  even with latest 5.3.0 version available at https://aws.amazon.com/solutions/implementations/qnabot-on-aws/

**Comment by ihmaws** [comment]
Hi @PawanLRN, can you please great a new issue with details to reproduce (fill out the bug request template as best you can). I'd like to take a look at this with a fresh bug report and not rely on this issue.
