### ISSUE TITLE
Stack update failed - update_rollback also failed!!!

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#97]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Wednesday Apr 25, 2018 at 20:06 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/20_

----

## Expected Behavior

Stack updates must work reliably

## Actual Behavior

Stack update for QnABot in WHHA account failed.  
This stack was intially created from private repo 'private-develop' branch, per JohnC instructions. 
Per further instructions from JohnC today, I attempted to 'update' the stack using latest commit from the 'develop' branch.

Update failed. Update_rollback also failed.

![image](https://user-images.githubusercontent.com/10953374/39269953-72fd9138-48a2-11e8-9ebc-e2dc560b378d.png)
 

## Steps to Reproduce the Problem

  1.  create stack from 'private-develop' branch
  2.  checkout 'develop' branch, build and update stack
  3.  observe failed update, and failed update_rollback

## Specifications

  - Version:
  - Platform:

**Comment by JohnCalhoun** [comment]
this was an issue with apigateway updating the media/types field. until we need to change that field again this should not be an issue
