### ISSUE TITLE
Markdown text should be always be displayed in chatbot UI even in Voice mode

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#98]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rstrahan](https://github.com/rstrahan)**
_Monday Apr 30, 2018 at 22:22 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/22_

----

## Expected Behavior

Markdown alt-text, if present, should *always* be used in Chatbot UI for text rendering - whether in text or voice mode.

## Actual Behavior

When using voice to ask a question that has a markdown alt-text answer, the chatbot UI displays the transcription of the voice response (which either comes from the standard answer field, or the SSML field if present).  The markdown field is not used as expected, thus defeating the requirement to be able to use different responses for voice and text displays.

## Steps to Reproduce the Problem

  1.  Add an item with answer and Markdown alt answer
  2.  Use voice mode in chatbot UI to retrieve answer
  3.  Observe that markdown text is not displayed

## Specifications

  - Version:
  - Platform:

**Comment by dontirun** [comment]
<a href="https://github.com/rstrahan"><img src="https://avatars0.githubusercontent.com/u/10953374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rstrahan](https://github.com/rstrahan)**
_Saturday May 19, 2018 at 20:39 GMT_

----

@JohnCalhoun  - I just tried testing this with the stack created from develop branch a couple of days ago, and it's not fixed.. Markdown was ignored in voice mode - see screenshot.

![image](https://user-images.githubusercontent.com/10953374/40272874-252e1b32-5b83-11e8-903b-55f6d772d69a.png)

**Comment by JohnCalhoun** [comment]
fixed in 2.1.0
